### ISSUE TITLE
Thanks :)

### ISSUE THREAD

**Issue by markmarijnissen** [stuartmemo/sympathetic-synth#2]
Just a quick note to say thanks.

For a little workshop/hackaton, I've hooked up your synth to a kinect - it just took 1.5 hours. If the synth wasn't already available, this would be impossible to do.

1. We added Socket.io - it listens to `playnote` messages to play notes
2. We created a NodeJS socket.io server, which converts Kinect Skeletal data to notes.
3. We added a Socket.io Client to the Kinect Skeletal Demo to send data as JSON.

 Now, we could wave our hands and hear the synth playing in the browser :)

**Comment by stuartmemo** [comment]
@markmarijnissen Hey just saw this. I hadn't set up notifications. That sounds amazing. My pleasure. Thanks for letting me know! :musical_keyboard:
